### ISSUE TITLE
on login: "attempt to call field 'CalcMd5' (a nil value)"

### ISSUE THREAD

**Issue by abma** [gajop/IngameLobby#1]
when trying to login i get the error

"attempt to call field 'CalcMd5' (a nil value)"

**Comment by gajop** [comment]
This isn't an error. That function just isn't available in Spring's official repo yet, and ever since kloot removed the ability to use plain text PW it needs to be used
https://github.com/gajop/spring/commit/721529de9a1409bb5f35ba929388bccab539f308#diff-5f29739c7ae7d3ecf551c2b3a25db0b7R107

**Comment by abma** [comment]
it is, as it makes the whole menu unusable :)

**Comment by gajop** [comment]
Well.. I never said it works with current Spring..
It's going to fail on a couple more things: pr-downloader callins aren't available upstreams and callouts are probably only available in spring/pr-downloader branch

**Comment by abma** [comment]
shouldn't that be on some todo-list (=open issue) then? :)

**Comment by gajop** [comment]
Fine.
TODO: https://springrts.com/mantis/view.php?id=4647 or implement/merge MD5 upstream

**Comment by gajop** [comment]
I assume this issue solved.
There's this little thing: https://github.com/spring/spring/commit/95a1cacaf5769f25159078d4f9913ef9c31f7b5b#commitcomment-14780248 but I guess that's just a mistake/something that will be reverted
